# Generated by Django 2.1 on 2018-09-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='category',
        ),
    ]
