# Generated by Django 2.1 on 2018-09-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20180917_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='name',
        ),
        migrations.AddField(
            model_name='campaign',
            name='cost_fixed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cost_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='discount_percent',
            field=models.FloatField(default=0.0),
        ),
    ]
