# Generated by Django 2.1 on 2018-09-25 08:29

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20180918_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='billing',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='FIXED_COST', max_length=100, no_check_for_status=True),
        ),
    ]
