# Generated by Django 2.1.2 on 2018-10-30 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0007_auto_20181030_1244'),
        ('core', '0006_auto_20181030_1244'),
        ('clients', '0005_campaign_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedInfluencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('billing', model_utils.fields.StatusField(choices=[('FIXED_COST', 'FIXED_COST'), ('PERCENTAGE', 'PERCENTAGE')], default='FIXED_COST', help_text='Choose between FIXED_COST, PERCENTAGE', max_length=100, no_check_for_status=True)),
                ('cost', models.FloatField(default=0.0)),
                ('discount', models.IntegerField(default=0)),
                ('day', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfluencerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('data_type', model_utils.fields.StatusField(blank=True, choices=[('RAW DATA', 'RAW DATA'), ('VALIDATED DATA', 'VALIDATED DATA')], default='RAW DATA', help_text='Choose between RAW DATA, VALIDATED DATA', max_length=100, no_check_for_status=True)),
                ('no_sales', models.FloatField(default=0.0)),
                ('day_sales', models.DateField()),
                ('assigned_influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='clients.AssignedInfluencer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelManagers(
            name='campaign',
            managers=[
                ('timeframed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='billing',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='FIXED_COST', help_text='Choose between FIXED_COST, PERCENTAGE', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='billing',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='FIXED_PRICE', help_text='Choose from FIXED_PRICE, REVENUE_SHARE, AGENCY', max_length=100, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='assignedinfluencer',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_influencer', to='clients.Campaign'),
        ),
        migrations.AddField(
            model_name='assignedinfluencer',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_influencer', to='core.PromoCode'),
        ),
        migrations.AddField(
            model_name='assignedinfluencer',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_influencer', to='influencers.Influencer'),
        ),
        migrations.AddField(
            model_name='assignedinfluencer',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_influencer', to='influencers.SocialAccount'),
        ),
    ]
