# Generated by Django 2.1.2 on 2018-10-31 15:56

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20181030_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerhistory',
            name='data_type',
            field=model_utils.fields.StatusField(blank=True, choices=[(0, 'dummy')], default='RAW_DATA', help_text='Choose between RAW DATA, VALIDATED DATA', max_length=100, no_check_for_status=True),
        ),
    ]
