# Generated by Django 2.1.2 on 2018-11-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20181031_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='influencerhistory',
            options={'verbose_name_plural': 'Influencer histories'},
        ),
    ]
