# Generated by Django 2.1.2 on 2018-11-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20181111_1505'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='campaign',
            managers=[
            ],
        ),
    ]
