# Generated by Django 2.1.2 on 2018-11-27 14:36

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20181112_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedinfluencer',
            name='billing',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='FIXED_COST', help_text='Choose between FIXED_COST, REVENUE_SHARE_FIXED, REVENUE_SHARE_PERCENTAGE', max_length=100, no_check_for_status=True),
        ),
    ]
