# Generated by Django 2.1.4 on 2019-01-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("clients", "0013_auto_20190114_1113")]

    operations = [migrations.RunSQL("DROP TABLE IF EXISTS clients_influencerpayment;")]
