# Generated by Django 2.1.4 on 2019-01-14 13:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_auto_20190114_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('day', models.DateField()),
                ('invoice', models.FileField(default='', upload_to='invoices/')),
                ('billing_status', model_utils.fields.StatusField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID')], default='UNPAID', max_length=100, no_check_for_status=True)),
                ('assigned_influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_payment', to='clients.AssignedInfluencer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
