# Generated by Django 2.1.4 on 2019-01-22 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0010_auto_20190109_1643'),
        ('clients', '0015_influencerpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerUnPaidNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('cost', models.FloatField(default=0.0)),
                ('day', models.DateField()),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_notification', to='influencers.Influencer')),
            ],
            options={
                'verbose_name_plural': 'Influencer upaid notifications',
                'ordering': ['influencer'],
            },
        ),
    ]
