# Generated by Django 2.1.4 on 2019-01-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_influencerunpaidnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerpayment',
            name='assigned_influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_payment', to='clients.AssignedInfluencer'),
        ),
    ]
