# Generated by Django 2.1.4 on 2019-01-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("clients", "0017_auto_20190122_1458")]

    def migrate_data(apps, schema_editor):
        InfluencerPayment = apps.get_model("clients", "InfluencerPayment")
        payments = InfluencerPayment.objects.filter(is_removed=True).all()
        for payment in payments:
            payment.billing_status = "UNPAID"
            payment.save()

    operations = [
        migrations.RunPython(migrate_data, reverse_code=migrations.RunPython.noop)
    ]
