# Generated by Django 2.1.4 on 2019-01-28 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_auto_20190123_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerpayment',
            name='assigned_influencer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_payment', to='clients.AssignedInfluencer'),
        ),
    ]
