# Generated by Django 2.1.4 on 2019-01-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_auto_20190128_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedinfluencer',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='influencerhistory',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='influencerpayment',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='influencerunpaidnotification',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_removed',
        ),
        migrations.AddField(
            model_name='assignedinfluencer',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='influencerhistory',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='influencerpayment',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='influencerunpaidnotification',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
