version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: influencers_local_django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: influencers_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"
    restart: unless-stopped

  redis:
    image: redis:3.2
    restart: unless-stopped

  celeryworker:
    <<: *django
    image: influencers_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker
    restart: unless-stopped

  celerybeat:
    <<: *django
    image: influencers_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat
    restart: unless-stopped

  flower:
    <<: *django
    image: influencers_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
    restart: unless-stopped
