# Generated by Django 2.1 on 2018-09-20 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='iban',
        ),
    ]
