# Generated by Django 2.1 on 2018-09-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_bank_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='swift',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
