# Generated by Django 2.1.2 on 2018-10-30 12:44

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180923_1109'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='promocode',
            managers=[
                ('timeframed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promocode',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialplatform',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
