# Generated by Django 2.1 on 2018-10-31 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20181030_1244'),
        ('core', '0006_auto_20181030_1244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PromoCode',
            new_name='Coupon',
        ),
    ]
