# Generated by Django 2.1.2 on 2018-11-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181031_0937'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='coupon',
            managers=[
            ],
        ),
    ]
