# Generated by Django 2.1.2 on 2018-12-02 12:05

from django.db import migrations, models
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181112_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='swift',
            field=models.CharField(max_length=11),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=partial_index.PartialIndex(fields=['swift', 'is_removed'], name='core_bank_swift_7b73b4_partial', unique=True, where=partial_index.PQ(is_removed=False)),
        ),
    ]
