# Generated by Django 2.1.4 on 2019-01-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181202_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='socialplatform',
            options={'ordering': ['name']},
        ),
    ]
