# Generated by Django 2.1.4 on 2019-01-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190109_1643'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bank',
            name='core_bank_swift_7b73b4_partial',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='socialplatform',
            name='is_removed',
        ),
        migrations.AddField(
            model_name='bank',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='socialplatform',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
