# Generated by Django 2.1.4 on 2019-01-30 14:17

from django.db import migrations
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190130_1305'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bank',
            index=partial_index.PartialIndex(fields=['swift', 'deleted'], name='core_bank_swift_db8a53_partial', unique=True, where=partial_index.PQ(deleted__isnull=True)),
        ),
    ]
