# Generated by Django 2.1 on 2018-09-04 15:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20180904_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50)),
                ('gender', model_utils.fields.StatusField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=100, no_check_for_status=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('account_number', models.CharField(max_length=50)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to='core.Bank')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to='core.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('username', models.CharField(max_length=50)),
                ('cost_currency', djmoney.models.fields.CurrencyField(choices=[('EGP', 'Egyptian Pound'), ('SAR', 'Saudi Riyal'), ('AED', 'UAE Dirham'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('cost', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='influencers.Influencer')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.SocialPlatform')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
