# Generated by Django 2.1 on 2018-09-17 14:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20180917_1432'),
        ('core', '0003_promocode'),
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('day', models.DateField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='clients.Campaign')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.PromoCode')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='influencers.Influencer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
