# Generated by Django 2.1 on 2018-09-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='account_number',
        ),
        migrations.AddField(
            model_name='influencer',
            name='IBAN',
            field=models.CharField(default='0000000000000000000000000000000000', max_length=34),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='influencer',
            name='account_holder_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
