# Generated by Django 2.1 on 2018-09-20 10:35

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_auto_20180920_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to='core.Bank'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to='core.Category'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='gender',
            field=model_utils.fields.StatusField(blank=True, choices=[(0, 'dummy')], default='MALE', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
