# Generated by Django 2.1 on 2018-09-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0005_auto_20180920_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='IBAN',
            field=models.CharField(max_length=34, unique=True),
        ),
    ]
