# Generated by Django 2.1.2 on 2018-10-30 12:44

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0006_auto_20180923_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='influencer',
        ),
        migrations.AddField(
            model_name='influencer',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='gender',
            field=model_utils.fields.StatusField(blank=True, choices=[(0, 'dummy')], default='MALE', help_text='Choose between MALE, FEMALE', max_length=100, no_check_for_status=True),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
