# Generated by Django 2.1.2 on 2018-12-02 12:08

from django.db import migrations, models
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0007_auto_20181030_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='IBAN',
            field=models.CharField(max_length=34),
        ),
        migrations.AddIndex(
            model_name='influencer',
            index=partial_index.PartialIndex(fields=['IBAN', 'is_removed'], name='influencers_IBAN_9a593f_partial', unique=True, where=partial_index.PQ(is_removed=False)),
        ),
    ]
