# Generated by Django 2.1.4 on 2018-12-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0008_auto_20181202_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='branch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
