# Generated by Django 2.1.4 on 2019-01-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0009_auto_20181231_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='influencer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'ordering': ['username']},
        ),
    ]
