# Generated by Django 2.1.4 on 2019-01-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0010_auto_20190109_1643'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='influencer',
            name='influencers_IBAN_9a593f_partial',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='is_removed',
        ),
        migrations.AddField(
            model_name='influencer',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
