# Generated by Django 2.1.4 on 2019-01-30 14:17

from django.db import migrations
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0011_auto_20190130_1305'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='influencer',
            index=partial_index.PartialIndex(fields=['IBAN', 'deleted'], name='influencers_IBAN_b20bd8_partial', unique=True, where=partial_index.PQ(deleted__isnull=True)),
        ),
    ]
