# Generated by Django 2.1 on 2018-09-02 13:16

from django.db import migrations
import influencers.users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180829_0953'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', influencers.users.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
