# Generated by Django 2.1.2 on 2018-10-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180902_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
