# Generated by Django 2.1.2 on 2018-12-02 12:09

from django.db import migrations
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181111_1505'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=partial_index.PartialIndex(fields=['email', 'is_removed'], name='users_user_email_49d5ad_partial', unique=True, where=partial_index.PQ(is_removed=False)),
        ),
    ]
