# Generated by Django 2.1.4 on 2019-01-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181202_1209'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_email_49d5ad_partial',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_removed',
        ),
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
