# Generated by Django 2.1.4 on 2019-01-30 14:17

from django.db import migrations
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190130_1305'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=partial_index.PartialIndex(fields=['email'], name='users_user_email_e23ff8_partial', unique=True, where=partial_index.PQ(deleted__isnull=True)),
        ),
    ]
