# Generated by Django 2.1.4 on 2019-02-05 11:01

from django.db import migrations
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190130_1417'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_email_e23ff8_partial',
        ),
        migrations.AddIndex(
            model_name='user',
            index=partial_index.PartialIndex(fields=['email', 'deleted'], name='users_user_email_aa11f0_partial', unique=True, where=partial_index.PQ(deleted__isnull=True)),
        ),
    ]
